name: Release Flow

on:
  workflow_dispatch:
    inputs:
      newVersion:
        description: 'New version'
        required: true
        default: 'invalid'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_TOKEN }}
      - name: Install dependencies
        uses: php-actions/composer@v5
      - name: Bump version
        uses: php-actions/composer@v5
        with:
          command: version-bump -- ${{ github.event.inputs.newVersion }}
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'composer.json'
          author_name: 'JobRouterBot'
          author_email: 'opensource@jobrouter.com'
          message: 'Bump version to ${{ github.event.inputs.newVersion }}'
          pull_strategy: 'NO-PULL'
          push: true
          remove: ''
          signoff: true
          tag: 'v${{ github.event.inputs.newVersion }}'
